# Generated by Django 5.2.12 on 2026-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_alter_flat_has_balcony"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="new_building",
            field=models.BooleanField(
                blank=True,
                help_text="Отметьте, если квартира находится в новом доме",
                null=True,
                verbose_name="Новостройка",
            ),
        ),
    ]
