# Generated by Django 5.2.9 on 2026-03-18 14:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_flat_owner_pure_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="user",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owner_pure_phone",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owners_phonenumber",
        ),
        migrations.AddField(
            model_name="complaint",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flat",
            name="owner_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="flat",
            name="owner_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="flat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="property.flat",
                verbose_name="Квартира",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="living_area",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Количество жилых кв.метров",
            ),
        ),
        migrations.AlterField(
            model_name="flat",
            name="new_building",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                help_text="Отметьте, если квартира находится в новом доме",
                null=True,
                verbose_name="Новостройка",
            ),
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ФИО собственника"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "phone_pure",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Номер телефона будет автоматически проверен и приведён к единому формату",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Нормализованный телефон собственника",
                    ),
                ),
                (
                    "flats",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owners",
                        to="property.flat",
                        verbose_name="Квартиры",
                    ),
                ),
            ],
        ),
    ]
