# Generated by Django 5.2.12 on 2026-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_fill_owner_pure_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ФИО собственника"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "flats",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owners",
                        to="property.flat",
                        verbose_name="Квартиры",
                    ),
                ),
            ],
        ),
    ]
